dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libcurl4-openssl-dev
      - openssl

script:
  - ls extern/sleepy-discord/lib/linux
  - ls extern/poco-1.9.0/lib/linux
  - cmake .
  - make VERBOSE=1
